#!/usr/bin/env bash
# a Bash script that displays:

for file in *; do
    if [[ ! "$file" == .* && -f "$file" ]]; then
        name_after_dash=$(echo "$file" | cut -d '-' -f 2-)
        echo "$name_after_dash"
    fi
done
